#!/bin/bash

# PLEASE read all the contents of this text file. Thank you.

# This file is licensed under GNU General Public License-3.0

# This .sh file creates a whole backup of your home folder. But you must edit the file below. Replace "edit-me" with your device name (find with lsblk and Gnome Disk Utility)

# If you have any other folder or files, add them too :)

# If you want to exclude any files/folders, add a # in front of the sentence and the following line.

# At last, to make this script to work, please make it execuable. Type in: chmod +x ./home/your-username/Path/to/backup-all-your-files.sh. Alter "/Path/to" with your folder."

if [[ -z "$@" ]] || [[ ! -z "$2" ]]; then

    echo "Invalid argument count."

fi

exit

echo "Mounting backup drive"

if [[ -f "/dev/$1" ]]; then

    echo "Invalid drive."

fi

sudo mount /dev/$1 "/media/$USER/$1-backup"

echo "Prepping directories..."

mkdir "/media/$USER/$1-rbackup/rbackup"

echo "Backing up your files...."

rsync -r ~/Documents "/media/$USER/$1-rbackup/rbackup" && echo "Documents folder has been backed up."

rsync -r ~/Downloads "/media/$USER/$1-rbackup/rbackup" && echo "Downloads folder has been backed up."

rsync -r ~/Music/ "/media/$USER/$1-rbackup/rbackup" && echo "Music folder has been backed up."

rsync -r ~/Pictures "/media/$USER/$1-rbackup/rbackup" && echo "Pictures folder has been backed up."

rsync -r ~/Public "/media/$USER/$1-rbackup/rbackup" && echo "Public folder has been backed up."

rsync -r ~/Templates "/media/$USER/$1-rbackup/rbackup" && echo "Templates folder has been backed up."

rsync -r ~/Videos "/media/$USER/$1-rbackup/rbackup" && echo "Videos folder has been backed up."

rsync -r ~/Desktop "/media/$USER/$1-rbackup/rbackup" && echo "Desktop has been backed up."

rsync -r ~/.config "/media/$USER/$1-rbackup/rbackup" && echo ".config has been backed up."

echo "Backup Done."
